language: node_js
node_js:
  - "4.2.0"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm install -g grunt-cli
  - npm install -g karma-cli
  - grunt

script:
  - karma start --single-run
